### ISSUE TITLE
Theme color override does not work

### ISSUE THREAD

**Issue by letatas** [twostraws/Ignite#206]
It seems that whatever you choose as a theme, it always takes the default Bootstrap one. Here's an example on how to reproduce:

- Create a new site from scratch
`ignite new test`

- Add a custom `Theme` with a custom `danger` color for example:
```swift
struct MyTheme: Theme {
    var name: String = "test"

    let danger: Color = .aliceBlue
}
```

- Add the new theme to the site:
```swift
struct ExampleSite: Site {    
    var name = "Hello World"
    var titleSuffix = " – My Awesome Site"
    var url = URL(static: "https://www.example.com")
    var builtInIconsEnabled = true

    var author = "John Appleseed"

    var homePage = Home()
    var layout = MainLayout()
    
    // Custom theme
    let lightTheme = MyTheme()
}
```

- Update the home page to use the customized `danger` color:
```swift
struct Home: StaticLayout {
    var title = "Home"

    var body: some HTML {
        Text("Hello world!")
            .font(.title1)
            .foregroundStyle(.danger)
    }
}
```

- Build and preview the site, the title will still be red and not blue :( 
`ignite build; ignite run --preview`

**Comment by twostraws** [comment]
I've just merged a bunch of PRs from @JPToroDev, and there are two more waiting to be merged. It's possible this might already be resolved?

**Comment by letatas** [comment]
Thank you for your fast answer, unfortunately with the current commit (#[3a345f9](https://github.com/twostraws/Ignite/commit/3a345f97a1b40c1ad2f2618f1681d6943ba0d886)) the theme system seems completely broken instead. 
No style is applied anymore 😞

**Comment by JPToroDev** [comment]
I'll take a look ASAP. Thank you for flagging!

**Comment by JPToroDev** [comment]
This should all be fixed in #215. Let me know if you're still encountering any issues.

**Comment by letatas** [comment]
Thank you @JPToroDev  for your help, but if I'm not mistaken it seems that the example above is still not functional on this last commit [#e22e2b2](https://github.com/twostraws/Ignite/commit/e22e2b2c5f721730df0549af8549321f6955a05b)

The only thing that I hade to change is passing the `name` property to `static` but the result is still unstyled.

**Comment by JPToroDev** [comment]
Thank you for following up. That commit fixed the issue, but caused a bug that keeps alternate themes from being exported. I've just made a PR with the fix. 🙌🏼

**Comment by letatas** [comment]
Hello, unfortunately, I'm afraid the styling is still broken even with the last commit I tested: [#30627c6](https://github.com/twostraws/Ignite/commit/30627c6ffdcc14da558e61e8139059a9c04ca9d4)

**Comment by JPToroDev** [comment]
Can you elaborate on what you're seeing?

**Comment by letatas** [comment]
Of course, with the example given in the first message of this ticket, (empty project, with only a specific theme overriding the `danger` color) instead of having the title in `aliceBlue` (new `danger` color) it's plain black, not even red.

<img width="197" alt="image" src="https://github.com/user-attachments/assets/ce204553-c2a4-4fab-b715-414b3104d9c2" />

But maybe I'm doing something wrong 🤷‍♂️

**Comment by JPToroDev** [comment]
Thank you! I notice a few possible issues:

For `Site`, you need to specify `lightTheme`'s type like this:

```swift
struct ExampleSite: Site {    
    var lightTheme: (any Theme)? = MyTheme()
}
```

Since this custom theme is for light mode, I'd conform to `LightTheme`. This ensure Bootstrap's default light mode-specific values are used, and that the correct `Material` variant is used if present.

```swift
struct MyTheme: LightTheme {
    var name: String = "test"
    let danger: Color = .aliceBlue
}
```

**Comment by letatas** [comment]
Thank you for your insight, unfortunately even with specifying the `(any Theme)?` type in the `Site` and the `LightTheme` conformance, I still have an unstylized page. (ie black & white)

Please tell me if I can help in any way.

**Comment by JPToroDev** [comment]
I've tested the following code, and it works as expected. Can you try running it in a fresh project?

```swift
struct MainLayout: Layout {
    @Environment(\.siteConfiguration) private var config
    var body: some HTML {
        HTMLDocument {
            HTMLHead(for: page, with: config)

            HTMLBody {
                Grid {
                    Section(page.body)
                }
            }
            .class("container")
        }
    }
}

struct Home: StaticLayout {
    var title = "Home"

    var body: some HTML {
        Text("Hello world!")
            .font(.title1)
            .foregroundStyle(.danger)
    }
}

struct MyTheme: LightTheme {
    static var name: String = "test"
    let danger: Color = .gold
}

struct ExampleSite: Site {
    var name = "Hello World"
    var titleSuffix = " – My Awesome Site"
    var url = URL(static: "https://www.example.com")
    var builtInIconsEnabled = true

    var author = "John Appleseed"
    var homePage = Home()
    var layout = MainLayout()
    var lightTheme: (any Theme)? = MyTheme()
}
```

**Comment by JPToroDev** [comment]
Can you try viewing your site in Incognito mode? Sometimes a caching issue will render an old version of the site.

**Comment by letatas** [comment]
Same result in private mode. But when I look at the end of the style file `themes.min.css` the value for the danger color is the same `--bs-danger: rgb(220 53 69 / 100%);` whatever the value you set in `MyTheme`

**Comment by JPToroDev** [comment]
OK, let me reopen this and investigate today. Thank you!

**Comment by JPToroDev** [comment]
Can you give #239 a try and let me know if it resolves this issue?

**Comment by letatas** [comment]
YEAH!!! It works!!! Gratz! 
The only thing is I needed to specify `var darkTheme: (any Theme)? = nil` otherwise the dark theme is auto-filled by the gitlab default!
But otherwise if completely works. Thanks a lot for your help, and sorry for not having been of a great help in the matter.

**Comment by JPToroDev** [comment]
Fantastic!

> The only thing is I needed to specify var darkTheme: (any Theme)? = nil otherwise the dark theme is auto-filled by the bootstrap default!

That's expected behavior and the correct way to disable a theme.

Bringing this issue to our attention was a *tremendous* help—thank you!
